const Airports = [
    {
      "code": "DEL",
      "lat": "28.5603",
      "lon": "77.1027",
      "name": "Indira Gandhi International Airport",
      "city": "Delhi",
      "state": "Delhi",
      "country": "India",
      "woeid": "12513599",
      "tz": "Asia\/Kolkata",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "12500",
      "elev": "776",
      "icao": "VIDP",
      "direct_flights": "95",
      "carriers": "70"
    },
    {
      "code": "DXB",
      "lat": "25.2509",
      "lon": "55.3629",
      "name": "Dubai International Airport",
      "city": "Dubai",
      "state": "Dubai",
      "country": "United Arab Emirates",
      "woeid": "23388362",
      "tz": "Asia\/Dubai",
      "phone": "+971 4 216 2525",
      "type": "Airports",
      "email": "",
      "url": "http:\/\/www.dubaiairport.com",
      "runway_length": "13123",
      "elev": "34",
      "icao": "OMDB",
      "direct_flights": "170",
      "carriers": "126"
    },
    {
      "code": "SIN",
      "lat": "1.3578",
      "lon": "103.991",
      "name": "Singapore Changi Airport",
      "city": "Singapore",
      "state": "South East",
      "country": "Singapore",
      "woeid": "12517525",
      "tz": "Asia\/Singapore",
      "phone": "(65) 6542 1122",
      "type": "Airports",
      "email": "",
      "url": "http:\/\/www.changiairport.com.sg\/",
      "runway_length": "13200",
      "elev": "65",
      "icao": "WSSS",
      "direct_flights": "108",
      "carriers": "80"
    },
    {
      "code": "HND",
      "lat": "35.5533",
      "lon": "139.771",
      "name": "Tokyo International Airport",
      "city": "Tokyo",
      "state": "Tokyo",
      "country": "Japan",
      "woeid": "23388311",
      "tz": "Asia\/Tokyo",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "http:\/\/www.tokyo-airport-bldg.co.jp\/",
      "runway_length": null,
      "elev": null,
      "icao": "KHND",
      "direct_flights": "55",
      "carriers": "19"
    },
    {
      "code": "IST",
      "lat": "40.9857",
      "lon": "28.8163",
      "name": "Ataturk Hava Limani Airport",
      "city": "Istanbul",
      "state": "Istanbul",
      "country": "Turkey",
      "woeid": "23388365",
      "tz": "Europe\/Istanbul",
      "phone": "",
      "type": "Airports",
      "email": "",
      "url": "",
      "runway_length": "9842",
      "elev": "157",
      "icao": "LTBA",
      "direct_flights": "157",
      "carriers": "79"
    },
    
  ]


  module.exports={Airports}